elso=float(input("kérem adjon meg az első számot:"))
masodik=float(input("kérem adja meg a második számot:"))
print("A két számod összege:",elso+masodik)
a=float(input("kérem adja meg a téglalap A oldalát:"))
b=float(input("kérem adja meg a téglalap B oldalát:"))
print("A téglalap kerülete",2*(a+b))
print("A téglalap területe:",a*b)

m=float(input("Kérem adja meg a magasságát m-ben:"))
tt=float(input("Kérem adja meg a súlyát kg-ben:"))
print(20*"*"+5*"-"+20*"*")
print("Az ön testtömeg indexe:",round(tt/(m)**2,2),"%")
print("Az ön sullyához ideális testömeg:",round(18.5*(m)**2,2),"KG és",round(24.9*(m)**2,2),"KG között van")

m=float(input("Kérem adja meg a magasságát m-ben:"))
tt=float(input("Kérem adja meg a súlyát kg-ben:"))
print(20*"*"+5*"-"+20*"*")
print("Az ön testtömeg indexe:",round(tt/(m)**2,2),"%")
print("Az ön sullyához ideális testömeg:",round(18.5*(m)**2,2),"KG és",round(24.9*(m)**2,2),"KG között van")